### ISSUE TITLE
How to arrange a multi-level object to be visualized?

### ISSUE THREAD

**Issue by hope-data-science** [neylsoncrepalde/multinets#2]
It's a great implementation to make such visualization. However, I find it hard to arrange my data to the form of `linked_sim`. Any examples to construct a `linked_sim` from a data.frame of edge list or igraph object?

**Comment by neylsoncrepalde** [comment]
Hello! 

Social network analysist are use to work with 1-mode networks (networks where nodes of the same nature have ties to each other -- people, organizations, countries, animals, computers, etc.) and 2-mode networks (afiiliation networks -- people who attended meetings, researchers who participated in congresses, people that work in organizations, etc.)

Multilevel networks put this all together. To give an extremely brief explanation, the rationale behind multilevel networks is that you have a lower network with ties among them (you can think of individuals here), you have an upper network with ties among them (you can think of organizations here) and the affiliation ties between the lower and upper levels (you can think of affiliation ties connecting individuals to their organizations) all at the same time.

[This paper](https://www.researchgate.net/publication/222408337_Catching_up_with_big_fish_in_the_big_pond_Multi-level_network_analysis_through_linked_design) by professor Emmanuel Lazega provides great explanations.

I´ll try to make available some datasets that I produced in my PhD research.
